#include <iostream>
#include <cstring>
#include "funciones.h"

using namespace std;

/**
LA FACULTAD REGIONAL PACHECO TIENE UNA CARRERA LLAMADA TUP
LA MISMA CUENTA CON 20 MATERIAS.
SE PIDE HACER UN PROGRAMA PARA ALMACENAR LOS NOMBRES, EL
NUMERO Y LA CANTIDAD DE PARCIALES QUE SE TOMA EN CADA UNA
EL PROGRAMA DEBE CONTAR CON UN MENU CON LAS SIGUIENTES OPCIONES:
-CARGAR DATOS MATERIAS.
-MOSTRAR DATOS MATERIAS.
-SALIR DEL PROGRAMA.
*/

int main(){
    setlocale(LC_ALL, "spanish");
    menu();
    return 0;
}
